### ISSUE TITLE
No 'data' key in response

### ISSUE THREAD

**Issue by egononega** [eapowertools/qsaas#1]
For example if you want to do something like `q.get("reloads/5fe1dbfc61df020001f5639b")` the response will be empty.
For now I changed the get method with:
```
result = r.json()
  if 'data' in result:
    result = r.json()['data']
```
Now I get a result.

Do with it what you want :)

**Comment by danielpilla** [comment]
Hello -- thanks for raising this -- I missed this in my testing. Resolved with the following script:

```
if r.status_code == 200:
    result = r.json()
    if 'data' in result:
        result = result['data']
```
