### ISSUE TITLE
Support for Qlik Enterprise on Win? 

### ISSUE THREAD

**Issue by lambdamusic** [eapowertools/qsaas#2]
Hi! Quick question - can I use this library with Qlik Enterprise on Win? I don't have 'keys' for auth so I was wondering about that..

Thanks in advance!

**Comment by danielpilla** [comment]
Hello,
This repository is specifically for working with Qlik Sense Enterprise SaaS. For QSEoW, I believe there are a couple wrappers floating around out there. This is one I am familiar of: [QlikSense python API client for QPS and QRS interfaces](https://developer.qlik.com/garden/570e73c36c8c33c066a0f11c) -- or of course you can always just use something like the [requests ](https://requests.readthedocs.io/en/master/) library and use vanilla Python.

Cheers,

**Comment by ljckennedy** [comment]
There is also [qrspy](https://github.com/clintcarr/qrspy) which is used by some big Qlik customers.  I have not compared the two, but have used this one in the past.

**Comment by lambdamusic** [comment]
Many thanks to both for the pointers. 
I'm quite new to Qlik so this is very useful to know.
